apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  # Replace ARGOCD_SERVER with your ArgoCD server name (see https://medium.com/dzerolabs/installing-ambassador-argocd-and-tekton-on-kubernetes-540aacc983b9)
  ARGOCD_SERVER: aaa364082be68423b8a5abebebcd1bad-1651913942.eu-west-1.elb.amazonaws.com
  ARGOCD_APPLICATION_NAME: tekton-pipeline-app
  ARGOCD_APPLICATION_REVISION: HEAD

